name: Build

on:
  push:
    branches: [ "**" ]

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Change wrapper permissions
        run: chmod +x mvn

      - name: Build with Maven
        run: ./mvnw verify